Support multilang mnemonic
Zondax/filecoin-signing-tools pull request #334
Opened 2020-11-19 14:05 UTC by rllola

closes https://github.com/Zondax/filecoin-signing-tools/issues/287

- [x] Added `language_code` argument
- [x] Update test
- [ ] Add test for chinese mnemonic

NOTE: breaking changes

2020-11-25 16:40 UTC, jleni commented
Hi @rllola, this seems to be breaking the current API?
I think it would be better to keep the same API and add a new function or when possible a default to English.
Otherwise, we will be breaking compatibility for some users.

2020-11-25 16:41 UTC, jleni requested changes
Hi @rllola, this seems to be breaking the current API?
I think it would be better to keep the same API and add a new function or when possible a default to English.
Otherwise, we will be breaking compatibility for some users.

2020-11-25 16:58 UTC, rllola commented
Yes, it is breaking the current API. I can do default for english for WASM I think but it would be breaking for rust.
The other solution is having new functions that let you change the language and the current one would keep English.

2020-11-26 12:38 UTC, jleni approved these changes

2020-11-26 12:39 UTC, merged